name: Update Angular Version in Confluence

on:
  push:
    paths:
      - 'package.json'  # Trigger only when package.json changes

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Angular version
        id: get-version
        run: |
          ANGULAR_VERSION=$(node -pe "require('./package.json').dependencies['@angular/core'] || 'Not found'")
          echo "ANGULAR_VERSION=$ANGULAR_VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$ANGULAR_VERSION"

      - name: Update Confluence Page
        run: |
          # Format the Confluence content (Storage Format)
          CONTENT='{
            "version": { "number": 2 },
            "title": "Angular Versions",
            "type": "page",
            "body": {
              "storage": {
                "value": "<p><strong>${{ github.repository }} Angular Version</strong></p><p>Version: <code>${{ env.ANGULAR_VERSION }}</code></p><p>Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")</p>",
                "representation": "storage"
              }
            }
          }'

          # Call Confluence REST API
          curl -X PUT \
            -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$CONTENT" \
            "https://${{ secrets.CONFLUENCE_DOMAIN }}/wiki/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}"