name: Update Angular Version in Confluence

on:
  push:
    paths:
      - 'package.json'

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Angular version
        id: get-version
        run: |
          ANGULAR_VERSION=$(node -pe "require('./package.json').dependencies['@angular/core'] || 'Not found'")
          echo "ANGULAR_VERSION=$ANGULAR_VERSION" >> $GITHUB_ENV
          # Escape JSON special characters
          ESCAPED_VERSION=$(node -pe "JSON.stringify(process.env.ANGULAR_VERSION)")
          echo "ESCAPED_VERSION=$ESCAPED_VERSION" >> $GITHUB_ENV

      - name: Update Confluence Page
        run: |
          CONTENT=$(cat <<EOF
          {
            "version": { "number": $(date +%s) },
            "title": "Angular Versions",
            "type": "page",
            "body": {
              "storage": {
                "value": "<p><strong>${{ github.repository }}</strong><br>Angular: <code>${{ env.ESCAPED_VERSION }}</code></p>",
                "representation": "storage"
              }
            }
          }
          EOF
          )
          
          curl -X PUT \
            -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$CONTENT" \
            "https://${{ secrets.CONFLUENCE_DOMAIN }}/wiki/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}"