name: Update Confluence Page

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Extract Angular version from package.json
      - name: Extract Angular Version
        id: extract_version
        run: |
          angular_version=$(jq -r '.dependencies["@angular/core"]' package.json)
          echo "ANGULAR_VERSION=$angular_version" >> $GITHUB_ENV

      # Step 3: Fetch the current Confluence page content
      - name: Fetch Confluence Page Content
        id: fetch_page
        env:
          CONFLUENCE_EMAIL: ${{ secrets.CONFLUENCE_EMAIL }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        run: |
          response=$(curl -s -u "$CONFLUENCE_EMAIL:$CONFLUENCE_API_TOKEN" \
            -X GET "https://raghavlahoti55.atlassian.net/wiki/rest/api/content/196609?expand=body.storage,version")
          echo "$response" > page.json
          version=$(jq -r '.version.number' page.json)
          echo "PAGE_VERSION=$version" >> $GITHUB_ENV

      # Step 4: Update the Confluence page with the new Angular version
      - name: Update Confluence Page
        env:
          CONFLUENCE_EMAIL: ${{ secrets.CONFLUENCE_EMAIL }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          ANGULAR_VERSION: ${{ env.ANGULAR_VERSION }}
          PAGE_VERSION: ${{ env.PAGE_VERSION }}
        run: |
          new_content="<h1>Version Update</h1><p>Updated Angular Version: <strong>$ANGULAR_VERSION</strong></p>"
          curl -s -u "$CONFLUENCE_EMAIL:$CONFLUENCE_API_TOKEN" \
            -X PUT "https://raghavlahoti55.atlassian.net/wiki/rest/api/content/196609" \
            -H "Content-Type: application/json" \
            -d '{
              "version": { "number": '"$((PAGE_VERSION + 1))"' },
              "title": "Version Update",
              "type": "page",
              "body": {
                "storage": {
                  "value": "'"$new_content"'",
                  "representation": "storage"
                }
              }
            }'